version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = [
    "frontend/Dockerfile",
    "backend/Dockerfile",
    "nlp/Dockerfile"
  ]

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "cypress",
    "browser",
    "nodejs"
  ]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
