DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS nlp_analyses CASCADE;
DROP TABLE IF EXISTS nlp_metadata CASCADE;
DROP TABLE IF EXISTS report_analyses_maps CASCADE;
DROP TABLE IF EXISTS report_metadata CASCADE;
