import DebugRedditUserInfo from "./DebugUserInfo";
import LoggedUserInfo from "./LoggedUserInfo";
import DebugSubredditInfo from "./DebugSubredditInfo";
import {Heading} from "@chakra-ui/react";
import {Await} from "react-router-dom";

/**
 * Dashboard page, gets user info asynchonously
 * @returns Promise<Element>
 */
const Dashboard = () => {
  return (
    <>
      <Heading as="h1">Dashboard</Heading>
      {/*/!* Lorem impsum added for testing purposes*!/purposes**/}
      {/*Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a ligula nec augue consequat venenatis. Fusce tellus sapien, dignissim non hendrerit at, auctor sed diam. Maecenas et lacus consequat, gravida orci vitae, accumsan ipsum. Duis imperdiet tellus sit amet imperdiet placerat. Phasellus tempor at odio at fermentum. Nunc non hendrerit dui. Nunc dapibus sed purus ut euismod. Phasellus mattis viverra velit et lacinia. Donec nec congue massa, finibus pretium turpis.*/}

      {/*Quisque nec dolor eget risus varius pharetra. Ut tempor aliquet nisi sed pellentesque. Morbi faucibus dui at condimentum rhoncus. Quisque vehicula pharetra magna lacinia vestibulum. Aenean non purus tincidunt, cursus quam vitae, eleifend nibh. Aliquam tristique sem ut felis sagittis dignissim. Vestibulum bibendum auctor eros, ut viverra leo aliquam vel. Proin iaculis porta sollicitudin. Praesent quis sem posuere, suscipit nisi non, efficitur neque. Aenean imperdiet sollicitudin elementum. Etiam placerat dignissim elit nec sollicitudin. Suspendisse potenti. Donec luctus condimentum neque vitae molestie. Sed vehicula laoreet lectus, id aliquam dolor euismod in. Aliquam accumsan bibendum odio. Vivamus ac est quis turpis fringilla pharetra posuere id est.*/}

      {/*Etiam sed iaculis dui. Integer lacinia laoreet orci, in dapibus diam tincidunt quis. Aenean laoreet nisi et dolor euismod, ac commodo urna imperdiet. Maecenas a tempor orci. Donec vehicula justo tristique metus posuere, at pellentesque dolor imperdiet. Donec aliquet gravida feugiat. Mauris dictum urna ac elit convallis varius. Phasellus nec varius massa. Mauris ultricies lacus quis est tempor, nec finibus arcu ornare. Quisque urna libero, luctus venenatis semper non, tincidunt nec felis. Quisque ultrices quam pellentesque tortor tempor rutrum. Aliquam rhoncus eros dui, sit amet sagittis elit semper non. Nullam iaculis elementum diam, ut ornare ipsum varius sed.*/}

      {/*Aliquam pretium vehicula ipsum, nec venenatis turpis viverra elementum. Ut iaculis felis nec leo elementum, eget lobortis est mollis. Etiam tincidunt ligula pellentesque, pharetra diam ut, aliquam ex. Morbi urna massa, iaculis vel suscipit eu, facilisis in turpis. Donec nec lectus eu nibh elementum tincidunt. Duis vel felis metus. Nulla faucibus quam at congue tincidunt. Aliquam quis aliquam ipsum. Proin at lorem iaculis, dictum urna et, rhoncus diam. Sed molestie accumsan purus, at blandit sapien consequat sed. Sed felis magna, pulvinar in consequat sed, venenatis non elit. Vestibulum metus libero, aliquet a dolor quis, dignissim dictum est. Quisque consectetur blandit iaculis.*/}

      {/*Etiam vehicula, erat a ullamcorper egestas, ante eros feugiat quam, sed ultricies quam tortor ac risus. Fusce blandit lorem non ultrices malesuada. Integer pellentesque eu urna nec rutrum. Aenean ultrices dui id nunc fermentum sagittis. Nam tristique dolor risus, nec ullamcorper lectus gravida sit amet. Cras vitae ante et lacus suscipit egestas. Quisque molestie magna ligula, egestas finibus ante posuere sed.*/}

      {/*Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a ligula nec augue consequat venenatis. Fusce tellus sapien, dignissim non hendrerit at, auctor sed diam. Maecenas et lacus consequat, gravida orci vitae, accumsan ipsum. Duis imperdiet tellus sit amet imperdiet placerat. Phasellus tempor at odio at fermentum. Nunc non hendrerit dui. Nunc dapibus sed purus ut euismod. Phasellus mattis viverra velit et lacinia. Donec nec congue massa, finibus pretium turpis.*/}

      {/*Quisque nec dolor eget risus varius pharetra. Ut tempor aliquet nisi sed pellentesque. Morbi faucibus dui at condimentum rhoncus. Quisque vehicula pharetra magna lacinia vestibulum. Aenean non purus tincidunt, cursus quam vitae, eleifend nibh. Aliquam tristique sem ut felis sagittis dignissim. Vestibulum bibendum auctor eros, ut viverra leo aliquam vel. Proin iaculis porta sollicitudin. Praesent quis sem posuere, suscipit nisi non, efficitur neque. Aenean imperdiet sollicitudin elementum. Etiam placerat dignissim elit nec sollicitudin. Suspendisse potenti. Donec luctus condimentum neque vitae molestie. Sed vehicula laoreet lectus, id aliquam dolor euismod in. Aliquam accumsan bibendum odio. Vivamus ac est quis turpis fringilla pharetra posuere id est.*/}

      {/*Etiam sed iaculis dui. Integer lacinia laoreet orci, in dapibus diam tincidunt quis. Aenean laoreet nisi et dolor euismod, ac commodo urna imperdiet. Maecenas a tempor orci. Donec vehicula justo tristique metus posuere, at pellentesque dolor imperdiet. Donec aliquet gravida feugiat. Mauris dictum urna ac elit convallis varius. Phasellus nec varius massa. Mauris ultricies lacus quis est tempor, nec finibus arcu ornare. Quisque urna libero, luctus venenatis semper non, tincidunt nec felis. Quisque ultrices quam pellentesque tortor tempor rutrum. Aliquam rhoncus eros dui, sit amet sagittis elit semper non. Nullam iaculis elementum diam, ut ornare ipsum varius sed.*/}

      {/*Aliquam pretium vehicula ipsum, nec venenatis turpis viverra elementum. Ut iaculis felis nec leo elementum, eget lobortis est mollis. Etiam tincidunt ligula pellentesque, pharetra diam ut, aliquam ex. Morbi urna massa, iaculis vel suscipit eu, facilisis in turpis. Donec nec lectus eu nibh elementum tincidunt. Duis vel felis metus. Nulla faucibus quam at congue tincidunt. Aliquam quis aliquam ipsum. Proin at lorem iaculis, dictum urna et, rhoncus diam. Sed molestie accumsan purus, at blandit sapien consequat sed. Sed felis magna, pulvinar in consequat sed, venenatis non elit. Vestibulum metus libero, aliquet a dolor quis, dignissim dictum est. Quisque consectetur blandit iaculis.*/}

      {/*Etiam vehicula, erat a ullamcorper egestas, ante eros feugiat quam, sed ultricies quam tortor ac risus. Fusce blandit lorem non ultrices malesuada. Integer pellentesque eu urna nec rutrum. Aenean ultrices dui id nunc fermentum sagittis. Nam tristique dolor risus, nec ullamcorper lectus gravida sit amet. Cras vitae ante et lacus suscipit egestas. Quisque molestie magna ligula, egestas finibus ante posuere sed.*/}
      {/*Lorem impsum added for testing purposes*/}
      {/*Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a ligula nec augue consequat venenatis. Fusce tellus sapien, dignissim non hendrerit at, auctor sed diam. Maecenas et lacus consequat, gravida orci vitae, accumsan ipsum. Duis imperdiet tellus sit amet imperdiet placerat. Phasellus tempor at odio at fermentum. Nunc non hendrerit dui. Nunc dapibus sed purus ut euismod. Phasellus mattis viverra velit et lacinia. Donec nec congue massa, finibus pretium turpis.*/}

      {/*Quisque nec dolor eget risus varius pharetra. Ut tempor aliquet nisi sed pellentesque. Morbi faucibus dui at condimentum rhoncus. Quisque vehicula pharetra magna lacinia vestibulum. Aenean non purus tincidunt, cursus quam vitae, eleifend nibh. Aliquam tristique sem ut felis sagittis dignissim. Vestibulum bibendum auctor eros, ut viverra leo aliquam vel. Proin iaculis porta sollicitudin. Praesent quis sem posuere, suscipit nisi non, efficitur neque. Aenean imperdiet sollicitudin elementum. Etiam placerat dignissim elit nec sollicitudin. Suspendisse potenti. Donec luctus condimentum neque vitae molestie. Sed vehicula laoreet lectus, id aliquam dolor euismod in. Aliquam accumsan bibendum odio. Vivamus ac est quis turpis fringilla pharetra posuere id est.*/}

      {/*Etiam sed iaculis dui. Integer lacinia laoreet orci, in dapibus diam tincidunt quis. Aenean laoreet nisi et dolor euismod, ac commodo urna imperdiet. Maecenas a tempor orci. Donec vehicula justo tristique metus posuere, at pellentesque dolor imperdiet. Donec aliquet gravida feugiat. Mauris dictum urna ac elit convallis varius. Phasellus nec varius massa. Mauris ultricies lacus quis est tempor, nec finibus arcu ornare. Quisque urna libero, luctus venenatis semper non, tincidunt nec felis. Quisque ultrices quam pellentesque tortor tempor rutrum. Aliquam rhoncus eros dui, sit amet sagittis elit semper non. Nullam iaculis elementum diam, ut ornare ipsum varius sed.*/}

      {/*Aliquam pretium vehicula ipsum, nec venenatis turpis viverra elementum. Ut iaculis felis nec leo elementum, eget lobortis est mollis. Etiam tincidunt ligula pellentesque, pharetra diam ut, aliquam ex. Morbi urna massa, iaculis vel suscipit eu, facilisis in turpis. Donec nec lectus eu nibh elementum tincidunt. Duis vel felis metus. Nulla faucibus quam at congue tincidunt. Aliquam quis aliquam ipsum. Proin at lorem iaculis, dictum urna et, rhoncus diam. Sed molestie accumsan purus, at blandit sapien consequat sed. Sed felis magna, pulvinar in consequat sed, venenatis non elit. Vestibulum metus libero, aliquet a dolor quis, dignissim dictum est. Quisque consectetur blandit iaculis.*/}

      {/*Etiam vehicula, erat a ullamcorper egestas, ante eros feugiat quam, sed ultricies quam tortor ac risus. Fusce blandit lorem non ultrices malesuada. Integer pellentesque eu urna nec rutrum. Aenean ultrices dui id nunc fermentum sagittis. Nam tristique dolor risus, nec ullamcorper lectus gravida sit amet. Cras vitae ante et lacus suscipit egestas. Quisque molestie magna ligula, egestas finibus ante posuere sed.*/}{/**/}

      {/*Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a ligula nec augue consequat venenatis. Fusce tellus sapien, dignissim non hendrerit at, auctor sed diam. Maecenas et lacus consequat, gravida orci vitae, accumsan ipsum. Duis imperdiet tellus sit amet imperdiet placerat. Phasellus tempor at odio at fermentum. Nunc non hendrerit dui. Nunc dapibus sed purus ut euismod. Phasellus mattis viverra velit et lacinia. Donec nec congue massa, finibus pretium turpis.*/}

      {/*Quisque nec dolor eget risus varius pharetra. Ut tempor aliquet nisi sed pellentesque. Morbi faucibus dui at condimentum rhoncus. Quisque vehicula pharetra magna lacinia vestibulum. Aenean non purus tincidunt, cursus quam vitae, eleifend nibh. Aliquam tristique sem ut felis sagittis dignissim. Vestibulum bibendum auctor eros, ut viverra leo aliquam vel. Proin iaculis porta sollicitudin. Praesent quis sem posuere, suscipit nisi non, efficitur neque. Aenean imperdiet sollicitudin elementum. Etiam placerat dignissim elit nec sollicitudin. Suspendisse potenti. Donec luctus condimentum neque vitae molestie. Sed vehicula laoreet lectus, id aliquam dolor euismod in. Aliquam accumsan bibendum odio. Vivamus ac est quis turpis fringilla pharetra posuere id est.*/}

      {/*Etiam sed iaculis dui. Integer lacinia laoreet orci, in dapibus diam tincidunt quis. Aenean laoreet nisi et dolor euismod, ac commodo urna imperdiet. Maecenas a tempor orci. Donec vehicula justo tristique metus posuere, at pellentesque dolor imperdiet. Donec aliquet gravida feugiat. Mauris dictum urna ac elit convallis varius. Phasellus nec varius massa. Mauris ultricies lacus quis est tempor, nec finibus arcu ornare. Quisque urna libero, luctus venenatis semper non, tincidunt nec felis. Quisque ultrices quam pellentesque tortor tempor rutrum. Aliquam rhoncus eros dui, sit amet sagittis elit semper non. Nullam iaculis elementum diam, ut ornare ipsum varius sed.*/}

      {/*Aliquam pretium vehicula ipsum, nec venenatis turpis viverra elementum. Ut iaculis felis nec leo elementum, eget lobortis est mollis. Etiam tincidunt ligula pellentesque, pharetra diam ut, aliquam ex. Morbi urna massa, iaculis vel suscipit eu, facilisis in turpis. Donec nec lectus eu nibh elementum tincidunt. Duis vel felis metus. Nulla faucibus quam at congue tincidunt. Aliquam quis aliquam ipsum. Proin at lorem iaculis, dictum urna et, rhoncus diam. Sed molestie accumsan purus, at blandit sapien consequat sed. Sed felis magna, pulvinar in consequat sed, venenatis non elit. Vestibulum metus libero, aliquet a dolor quis, dignissim dictum est. Quisque consectetur blandit iaculis.*/}

      {/*Etiam vehicula, erat a ullamcorper egestas, ante eros feugiat quam, sed ultricies quam tortor ac risus. Fusce blandit lorem non ultrices malesuada.malesuada*/}
      {/* <LoggedUserInfo />
      <DebugRedditUserInfo />
      <DebugSubredditInfo /> */}
    </>
  );
};

export default Dashboard;
