name: Rust Backend

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: echo $CLIENT_ID && echo $CLIENT_SECRET && cargo test --verbose
