name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: xmoods-api

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose


  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: xmoods-api

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose

  doc:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: xmoods-api

    steps:
    - uses: actions/checkout@v3
    - name: Build documentation
      run: cargo doc --document-private-items --workspace --no-deps