name: NextJS

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./xmoods-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21.x
      - run: npm ci
      - run: npm run test
      - run: npm run build-docs
