name: NextJS Frontend

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.5.1
      - run: npm ci --force # use --force while NextJS 15 is still RC
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.5.1
      - run: npm ci --force # use --force while NextJS 15 is still RC
      - run: npm run e2e:headless
