name: Python-NLP CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: xmoods-nlp

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: xmoods-nlp
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  doc:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: xmoods-nlp

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup sphinx
        run: |
          mkdir src/docs && cd src/docs
          sphinx-quickstart -q --no-sep -p xmoods-nlp -a Xmoods -r 0.1.0 -l en --ext-autodoc --ext-todo --ext-viewcode
          sed -i "s|#*html_theme = '.*'|html_theme = 'sphinx_rtd_theme'|g" conf.py
          sed -i "1i \import os\nimport sys\nsys.path.insert(0, os.path.abspath('..'))" conf.py
          cd ..
          sphinx-apidoc -o docs .
          cd docs
          sed -i "/:caption: Contents:/a\\\n   modules" index.rst

      - name: Make the sphinx docs
        working-directory: xmoods-nlp/src/docs
        run: |
          make clean
          make html
