on:
  push:
    branches:
      - ['210-setup-percy']
jobs:
  name: CI
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
      - run: npm ci
      - run: npm run build
      - run: percy exec -- npx cypress run --headless
        env:
          PERCY_TOKEN: $